spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Sampledatabase
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: /WEB-INF/views/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
server:
  servlet:
    session:
      timeout: 120s
